export const USER_DID_SIGNIN = 'USER_DID_SIGNIN';
export const USER_DID_SIGNOUT = 'USER_DID_SIGNOUT';
export const USER_DID_CHANGE = 'USER_DID_CHANGE';
export const LOCATION_DID_CHANGE = 'LOCATION_DID_CHANGE';
export const RECEIVE_USERINFO = 'RECEIVE_USERINFO';
