<?php

namespace App\Models;

use App\Models\Traits\HasDates;
use App\Models\Traits\HasImageAttribute;
use App\Models\Traits\HasThumbAttribute;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;


/**
 * App\Models\Cart
 *
 * @property int $id 主键
 * @property int $uid 用户ID
 * @property int $itemid 产品ID
 * @property string|null $title 产品名称
 * @property int $quantity 产品数量
 * @property string $price 商品价格
 * @property string $thumb 小图
 * @property string $image 大图
 * @property int $sku_id skuID
 * @property string|null $sku_title sku描述
 * @property \Illuminate\Support\Carbon|null $created_at 创建时间
 * @property \Illuminate\Support\Carbon|null $updated_at 修改时间
 * @property-read \App\Models\ProductItem $product
 * @property-read \App\Models\ProductSku|null $sku
 * @property-read \App\Models\User $user
 * @method static Builder|Cart groupByShop()
 * @method static Builder|Cart newModelQuery()
 * @method static Builder|Cart newQuery()
 * @method static Builder|Cart query()
 * @method static Builder|Cart whereCreatedAt($value)
 * @method static Builder|Cart whereId($value)
 * @method static Builder|Cart whereImage($value)
 * @method static Builder|Cart whereItemid($value)
 * @method static Builder|Cart wherePrice($value)
 * @method static Builder|Cart whereQuantity($value)
 * @method static Builder|Cart whereSkuId($value)
 * @method static Builder|Cart whereSkuTitle($value)
 * @method static Builder|Cart whereThumb($value)
 * @method static Builder|Cart whereTitle($value)
 * @method static Builder|Cart whereUid($value)
 * @method static Builder|Cart whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Cart extends Model
{
    use HasImageAttribute, HasThumbAttribute, HasDates;

    protected $table = 'cart';
    protected $primaryKey = 'id';
    protected $fillable = [
        'uid', 'itemid', 'title', 'quantity', 'price', 'thumb', 'image', 'sku_id', 'sku_title'
    ];
    protected $casts = [
        'quantity' => 'int',
        'sku_id' => 'int'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Cart $cart) {
            if (!$cart->uid) $cart->uid = Auth::id() ?? 0;
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'uid', 'uid');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product()
    {
        return $this->belongsTo(ProductItem::class, 'itemid', 'itemid');
    }

    /**
     * @param Builder $query
     * @return Builder
     */
    public function scopeGroupByShop(Builder $query)
    {
        return $query->groupBy('shop_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function sku()
    {
        return $this->hasOne(ProductSku::class, 'sku_id', 'sku_id');
    }
}
