<?php

namespace App\Models;


use App\Models\Traits\HasDates;
use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


/**
 * App\Models\CommonMaterial
 *
 * @property int $id
 * @property int $uid
 * @property string|null $name
 * @property string $thumb
 * @property string $source
 * @property string|null $width
 * @property string|null $height
 * @property string|null $type
 * @property string|null $extension 扩展名
 * @property int $size
 * @property string|null $mime
 * @property int $views
 * @property int $downloads
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read int|string $formated_size
 * @property-read string $image
 * @property-read \App\Models\User|null $user
 * @method static Builder|CommonMaterial doc()
 * @method static Builder|CommonMaterial file()
 * @method static Builder|CommonMaterial filter(array $input = [], $filter = null)
 * @method static Builder|CommonMaterial image()
 * @method static Builder|CommonMaterial newModelQuery()
 * @method static Builder|CommonMaterial newQuery()
 * @method static Builder|CommonMaterial paginateFilter($perPage = null, $columns = [], $pageName = 'page', $page = null)
 * @method static Builder|CommonMaterial query()
 * @method static Builder|CommonMaterial simplePaginateFilter(?int $perPage = null, ?int $columns = [], ?int $pageName = 'page', ?int $page = null)
 * @method static Builder|CommonMaterial video()
 * @method static Builder|CommonMaterial voice()
 * @method static Builder|CommonMaterial whereBeginsWith(string $column, string $value, string $boolean = 'and')
 * @method static Builder|CommonMaterial whereCreatedAt($value)
 * @method static Builder|CommonMaterial whereDownloads($value)
 * @method static Builder|CommonMaterial whereEndsWith(string $column, string $value, string $boolean = 'and')
 * @method static Builder|CommonMaterial whereExtension($value)
 * @method static Builder|CommonMaterial whereHeight($value)
 * @method static Builder|CommonMaterial whereId($value)
 * @method static Builder|CommonMaterial whereLike(string $column, string $value, string $boolean = 'and')
 * @method static Builder|CommonMaterial whereMime($value)
 * @method static Builder|CommonMaterial whereName($value)
 * @method static Builder|CommonMaterial whereSize($value)
 * @method static Builder|CommonMaterial whereSource($value)
 * @method static Builder|CommonMaterial whereThumb($value)
 * @method static Builder|CommonMaterial whereType($value)
 * @method static Builder|CommonMaterial whereUid($value)
 * @method static Builder|CommonMaterial whereUpdatedAt($value)
 * @method static Builder|CommonMaterial whereViews($value)
 * @method static Builder|CommonMaterial whereWidth($value)
 * @mixin \Eloquent
 */
class CommonMaterial extends Model
{
    use Filterable, HasDates;

    protected $table = 'common_material';
    protected $primaryKey = 'id';
    protected $fillable = [
        'uid', 'name', 'source', 'thumb', 'width', 'height', 'type', 'extension', 'size', 'views', 'downloads', 'mime'
    ];
    protected $appends = [
        'formated_size',
        'image'
    ];
    protected $with = ['user'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (CommonMaterial $material) {
            if (!$material->uid) $material->uid = Auth::id();
        });

        static::deleting(function (CommonMaterial $material) {
            Storage::delete($material->getRawOriginal('thumb'));
            Storage::delete($material->getRawOriginal('source'));
        });
    }

    /**
     * @param $value
     * @return string
     */
    public function getThumbAttribute($value)
    {
        if ($this->type == 'image') {
            return $value ? image_url($value) : $value;
        }

        if ($this->type == 'video') {
            return asset('images/common/video.png');
        }

        if ($this->type == 'voice') {
            return asset('images/common/audio.png');
        }

        if ($this->type == 'doc') {
            return asset('images/common/doc.png');
        }

        return asset('images/common/file.png');
    }

    /**
     * @param $value
     */
    public function setThumbAttribute($value)
    {
        $this->attributes['thumb'] = strip_image_url($value);
    }

    /**
     * @param $value
     * @return string
     */
    public function getImageAttribute()
    {
        return $this->source ? image_url($this->source) : null;
    }


    /**
     * @param $value
     * @return string
     */
    public function getSourceAttribute($value)
    {
        return $value ? material_url($value) : $value;
    }

    /**
     * @param $value
     */
    public function setSourceAttribute($value)
    {
        $this->attributes['source'] = strip_image_url($value);
    }

    /**
     * @return int|string
     */
    public function getFormatedSizeAttribute()
    {
        return $this->size ? format_size($this->size) : 0;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'uid', 'uid');
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeImage(Builder $query)
    {
        return $query->where('type', 'image');
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeVideo(Builder $query)
    {
        return $query->where('type', 'video');
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeVoice(Builder $query)
    {
        return $query->where('type', 'voice');
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeDoc(Builder $query)
    {
        return $query->where('type', 'doc');
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeFile(Builder $query)
    {
        return $query->where('type', 'file');
    }
}
