<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;


/**
 * App\Models\CommonMenu
 *
 * @property int $id 主键
 * @property string|null $name 名称
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\CommonMenuItem[] $items
 * @property-read int|null $items_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\CommonMenuItem[] $visibleItems
 * @property-read int|null $visible_items_count
 * @method static Builder|CommonMenu newModelQuery()
 * @method static Builder|CommonMenu newQuery()
 * @method static Builder|CommonMenu query()
 * @method static Builder|CommonMenu whereId($value)
 * @method static Builder|CommonMenu whereName($value)
 * @mixin \Eloquent
 */
class CommonMenu extends Model
{
    protected $table = 'common_menu';
    protected $primaryKey = 'id';
    protected $fillable = ['name'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function (CommonMenu $menu) {
            $menu->items()->delete();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function items()
    {
        return $this->hasMany(CommonMenuItem::class, 'menu_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function visibleItems()
    {
        return $this->hasMany(CommonMenuItem::class, 'menu_id', 'id')->where('hide', 0);
    }
}
