<?php

namespace App\Models;

use App\Models\Traits\HasImageAttribute;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;


/**
 * App\Models\CommonLink
 *
 * @property int $id 主键
 * @property int $cate_id 分类ID
 * @property string $type 类型
 * @property string|null $title 标题
 * @property string|null $url 链接
 * @property string $image 图片
 * @property string|null $description 描述
 * @property int $sort_num 排序
 * @property-read CommonLink|null $category
 * @property-read \Illuminate\Database\Eloquent\Collection<int, CommonLink> $links
 * @property-read int|null $links_count
 * @method static Builder|CommonLink newModelQuery()
 * @method static Builder|CommonLink newQuery()
 * @method static Builder|CommonLink onlyCategory()
 * @method static Builder|CommonLink onlyLink()
 * @method static Builder|CommonLink query()
 * @method static Builder|CommonLink whereCateId($value)
 * @method static Builder|CommonLink whereDescription($value)
 * @method static Builder|CommonLink whereId($value)
 * @method static Builder|CommonLink whereImage($value)
 * @method static Builder|CommonLink whereSortNum($value)
 * @method static Builder|CommonLink whereTitle($value)
 * @method static Builder|CommonLink whereType($value)
 * @method static Builder|CommonLink whereUrl($value)
 * @mixin \Eloquent
 */
class CommonLink extends Model
{
    use HasImageAttribute;

    protected $table = 'common_link';
    protected $primaryKey = 'id';
    protected $fillable = ['cate_id', 'type', 'title', 'url', 'image', 'description', 'sort_num'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderBy('sort_num')->orderBy('id');
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function links()
    {
        return $this->hasMany(CommonLink::class, 'cate_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(CommonLink::class, 'cate_id', 'id');
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopeOnlyCategory(Builder $builder)
    {
        return $builder->where('type', 'category');
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopeOnlyLink(Builder $builder)
    {
        return $builder->where('type', 'item');
    }
}
