<?php

namespace App\Models;

use App\Models\Traits\HasImageAttribute;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;


/**
 * App\Models\CommonBlockItem
 *
 * @property int $id 主键
 * @property int $block_id 块ID
 * @property string|null $title 标题
 * @property string $image 图片
 * @property string|null $url 链接
 * @property string|null $subtitle 副标题
 * @property string|null $field_1
 * @property string|null $field_2
 * @property string|null $field_3
 * @property int|null $sort_num 显示顺序
 * @property-read \App\Models\CommonBlock|null $block
 * @method static Builder|CommonBlockItem newModelQuery()
 * @method static Builder|CommonBlockItem newQuery()
 * @method static Builder|CommonBlockItem query()
 * @method static Builder|CommonBlockItem whereBlockId($value)
 * @method static Builder|CommonBlockItem whereField1($value)
 * @method static Builder|CommonBlockItem whereField2($value)
 * @method static Builder|CommonBlockItem whereField3($value)
 * @method static Builder|CommonBlockItem whereId($value)
 * @method static Builder|CommonBlockItem whereImage($value)
 * @method static Builder|CommonBlockItem whereSortNum($value)
 * @method static Builder|CommonBlockItem whereSubtitle($value)
 * @method static Builder|CommonBlockItem whereTitle($value)
 * @method static Builder|CommonBlockItem whereUrl($value)
 * @mixin \Eloquent
 */
class CommonBlockItem extends Model
{
    use HasImageAttribute;

    protected $table = 'common_block_item';
    protected $primaryKey = 'id';
    protected $fillable = ['block_id', 'title', 'image', 'url', 'subtitle', 'field_1', 'field_2', 'field_3', 'sort_num'];
    protected $hidden = ['block_id'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderByDesc('sort_num')->orderBy('id');
        });
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function block()
    {
        return $this->belongsTo(CommonBlock::class, 'block_id', 'id');
    }
}
