<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;


/**
 * App\Models\District
 *
 * @property int $id ID
 * @property int $parent_id 父级ID
 * @property string|null $name 名称
 * @property string|null $fullname 全称
 * @property int $level 级别
 * @property float|null $lng 经度
 * @property float|null $lat 纬度
 * @property string|null $pinyin 拼音
 * @property string|null $letter 首字母
 * @property string|null $zonecode 区位代码
 * @property string|null $citycode 区号
 * @property string|null $zipcode 邮编
 * @property int $sort_num 排序
 * @property-read \Illuminate\Database\Eloquent\Collection|District[] $children
 * @property-read int|null $children_count
 * @property-read \Illuminate\Database\Eloquent\Collection|District[] $childs
 * @property-read int|null $childs_count
 * @property-read District $parent
 * @method static Builder|District newModelQuery()
 * @method static Builder|District newQuery()
 * @method static Builder|District query()
 * @method static Builder|District whereCitycode($value)
 * @method static Builder|District whereFullname($value)
 * @method static Builder|District whereId($value)
 * @method static Builder|District whereLat($value)
 * @method static Builder|District whereLetter($value)
 * @method static Builder|District whereLevel($value)
 * @method static Builder|District whereLng($value)
 * @method static Builder|District whereName($value)
 * @method static Builder|District whereParentId($value)
 * @method static Builder|District wherePinyin($value)
 * @method static Builder|District whereSortNum($value)
 * @method static Builder|District whereZipcode($value)
 * @method static Builder|District whereZonecode($value)
 * @mixin \Eloquent
 */
class District extends Model
{
    protected $table = 'district';
    protected $primaryKey = 'id';
    protected $fillable = [
        'parent_id', 'name', 'fullname', 'level', 'lng', 'lat', 'pinyin', 'letter', 'zonecode', 'citycode', 'zipcode', 'sort_num'
    ];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderBy('sort_num')->orderBy('id');
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function childs()
    {
        return $this->hasMany(District::class, 'parent_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->childs()->with('children');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo(District::class, 'parent_id', 'id');
    }
}
