<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\EcomProductAttr
 *
 * @property int $attr_cate_id 属性分类ID
 * @property string|null $attr_title 属性名称
 * @property int $shop_id 门店ID
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\EcomProductAttrValue[] $attrValues
 * @property-read int|null $attr_values_count
 * @property-read \App\Models\EcomShop|null $shop
 * @method static \Illuminate\Database\Eloquent\Builder|EcomProductAttr newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|EcomProductAttr newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|EcomProductAttr query()
 * @method static \Illuminate\Database\Eloquent\Builder|EcomProductAttr whereAttrCateId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|EcomProductAttr whereAttrTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|EcomProductAttr whereShopId($value)
 * @mixin \Eloquent
 */
class EcomProductAttr extends Model
{
    protected $table = 'ecom_product_attr';
    protected $primaryKey = 'attr_cate_id';
    protected $fillable = ['attr_title', 'shop_id'];
    protected $with = ['attrValues'];
    protected $hidden = ['shop_id'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function (EcomProductAttr $productAttr) {
            $productAttr->attrValues()->delete();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attrValues()
    {
        return $this->hasMany(EcomProductAttrValue::class, 'attr_cate_id', 'attr_cate_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function shop()
    {
        return $this->belongsTo(EcomShop::class, 'shop_id', 'shop_id');
    }
}
