<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\ItemReviews
 *
 * @property int $id
 * @property int $uid
 * @property int $itemid
 * @property int $order_id
 * @property int $rate_type 1=好评,2=中评,3=差评
 * @property int $stars
 * @property string|null $message
 * @property \Illuminate\Database\Eloquent\Collection|\App\Models\ItemReviewsImage[] $images
 * @property int $image_count
 * @property string|null $created_at
 * @property string|null $add_message
 * @property string|null $add_images
 * @property string|null $add_at
 * @property int $add_image_count
 * @property string|null $seller_message
 * @property-read int|null $images_count
 * @property-read \App\Models\Item $item
 * @property-read \App\Models\Order $order
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereAddAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereAddImageCount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereAddImages($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereAddMessage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereImageCount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereImages($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereItemid($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereMessage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereOrderId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereRateType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereSellerMessage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereStars($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\ItemReviews whereUid($value)
 * @mixin \Eloquent
 */
class ItemReviews extends Model
{
    protected $table = 'item_reviews';
    protected $primaryKey = 'id';
    protected $fillable = [
        'uid','itemid','order_id','rate_type','stars','message','images',
        'image_count','created_at','add_message','add_images',
        'add_at','add_image_count','seller_message'
    ];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            if (!$model->created_at) $model->created_at = time();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function order()
    {
        return $this->belongsTo(Order::class, 'order_id', 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'uid', 'uid');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function item()
    {
        return $this->belongsTo(Item::class, 'itemid', 'itemid');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany(ItemReviewsImage::class, 'review_id', 'id');
    }
}
