<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\PageCategory
 *
 * @property int $cate_id 分类ID
 * @property string|null $cate_name 分类名称
 * @property int $sort_num 显示顺序
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Page[] $pages
 * @property-read int|null $pages_count
 * @method static Builder|PageCategory newModelQuery()
 * @method static Builder|PageCategory newQuery()
 * @method static Builder|PageCategory query()
 * @method static Builder|PageCategory whereCateId($value)
 * @method static Builder|PageCategory whereCateName($value)
 * @method static Builder|PageCategory whereSortNum($value)
 * @mixin \Eloquent
 */
class PageCategory extends Model
{
    protected $table = 'page_category';
    protected $primaryKey = 'cate_id';
    protected $fillable = ['cate_name', 'sort_num'];
    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderBy('sort_num')->orderBy('cate_id');
        });
        static::deleting(function (PageCategory $category) {
            $category->pages()->delete();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function pages()
    {
        return $this->hasMany(Page::class, 'cate_id', 'cate_id');
    }
}
