<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\ProductAttr
 *
 * @property int $attr_cate_id 属性分类ID
 * @property string|null $attr_title 属性名称
 * @property int $shop_id 门店ID
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProductAttrValue[] $attrValues
 * @property-read int|null $attr_values_count
 * @property-read \App\Models\Shop $shop
 * @method static \Illuminate\Database\Eloquent\Builder|ProductAttr newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|ProductAttr newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|ProductAttr query()
 * @method static \Illuminate\Database\Eloquent\Builder|ProductAttr whereAttrCateId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|ProductAttr whereAttrTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|ProductAttr whereShopId($value)
 * @mixin \Eloquent
 */
class ProductAttr extends Model
{
    protected $table = 'product_attr';
    protected $primaryKey = 'attr_cate_id';
    protected $fillable = ['attr_title', 'shop_id'];
    protected $with = ['attrValues'];
    protected $hidden = ['shop_id'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function (ProductAttr $productAttr) {
            $productAttr->attrValues()->delete();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attrValues()
    {
        return $this->hasMany(ProductAttrValue::class, 'attr_cate_id', 'attr_cate_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function shop()
    {
        return $this->belongsTo(Shop::class, 'shop_id', 'shop_id');
    }
}
