<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;


/**
 * App\Models\Address
 *
 * @property int $id 主键
 * @property int $uid 用户ID
 * @property string|null $tag 标签
 * @property string|null $name 姓名
 * @property string|null $phone 电话
 * @property string|null $province 省
 * @property string|null $city 市
 * @property string|null $district 区县
 * @property string|null $street 详细地址
 * @property float $latitude 纬度
 * @property float $longitude 经度
 * @property string|null $postalcode 邮编
 * @property int $isdefault 是否默认地址
 * @property-read string $formatted_address
 * @property-read \App\Models\User|null $user
 * @method static Builder|UserAddress newModelQuery()
 * @method static Builder|UserAddress newQuery()
 * @method static Builder|UserAddress query()
 * @method static Builder|UserAddress whereCity($value)
 * @method static Builder|UserAddress whereDistrict($value)
 * @method static Builder|UserAddress whereId($value)
 * @method static Builder|UserAddress whereIsdefault($value)
 * @method static Builder|UserAddress whereLatitude($value)
 * @method static Builder|UserAddress whereLongitude($value)
 * @method static Builder|UserAddress whereName($value)
 * @method static Builder|UserAddress wherePhone($value)
 * @method static Builder|UserAddress wherePostalcode($value)
 * @method static Builder|UserAddress whereProvince($value)
 * @method static Builder|UserAddress whereStreet($value)
 * @method static Builder|UserAddress whereTag($value)
 * @method static Builder|UserAddress whereUid($value)
 * @mixin \Eloquent
 */
class UserAddress extends Model
{
    protected $table = 'user_address';
    protected $primaryKey = 'id';
    protected $fillable = [
        'uid', 'name', 'phone', 'province', 'city', 'district', 'street',
        'postalcode', 'isdefault', 'gender', 'tag', 'latitude', 'longitude'
    ];
    protected $appends = ['formatted_address'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (UserAddress $address) {
            if (!$address->uid) $address->uid = Auth::id();
        });
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderByDesc('isdefault')->orderBy('id');
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'uid', 'uid');
    }

    /**
     * @return string
     */
    public function getFormattedAddressAttribute()
    {
        if ($this->province == $this->city) {
            return $this->city . $this->district . $this->street;
        }
        return $this->province . $this->city . $this->district . $this->street;
    }
}
