<?php

namespace App\Models;

use App\Services\Contracts\AccountServiceInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * App\Models\Account
 *
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|UserAccount newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|UserAccount newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|UserAccount query()
 * @mixin \Eloquent
 */
class UserAccount extends Model
{
    protected $table = 'user_account';
    protected $primaryKey = 'uid';
    protected $fillable = ['uid', 'password', 'balance', 'freeze', 'total_income', 'total_cost', 'points'];
    protected $hidden = ['password'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (UserAccount $account) {
            if (!$account->uid) $account->uid = Auth::id();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'uid', 'uid');
    }

    /**
     * @return mixed|null
     */
    public function getPaymentPassword()
    {
        return $this->password;
    }

    /**
     * @param $amount
     * @return mixed
     */
    public function incrementBalance($amount)
    {
        return app(AccountServiceInterface::class)->incrementBalance($this, $amount);
    }

    /**
     * @param $amount
     * @return mixed
     */
    public function decrementBalance($amount)
    {
        return app(AccountServiceInterface::class)->decrementBalance($this, $amount);
    }

    /**
     * @param $amount
     * @return mixed
     */
    public function incrementFreeze($amount)
    {
        return app(AccountServiceInterface::class)->incrementFreeze($this, $amount);
    }

    /**
     * @param $amount
     * @return mixed
     */
    public function decrementFreeze($amount)
    {
        return app(AccountServiceInterface::class)->decrementFreeze($this, $amount);
    }

    /**
     * @param $amount
     * @return mixed
     */
    public function freeze($amount)
    {
        return app(AccountServiceInterface::class)->freeze($this, $amount);
    }

    /**
     * @param $amount
     * @return mixed
     */
    public function unFreeze($amount)
    {
        return app(AccountServiceInterface::class)->unFreeze($this, $amount);
    }
}
