<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\WechatMenu
 *
 * @property int $id
 * @property int $fid
 * @property string|null $name
 * @property string|null $type
 * @property string|null $key
 * @property string|null $media_id
 * @property string|null $url
 * @property string|null $appid
 * @property string|null $pagepath
 * @property int $displayorder
 * @property-read \Illuminate\Database\Eloquent\Collection|WechatMenu[] $children
 * @property-read int|null $children_count
 * @property-read array|\Illuminate\Contracts\Translation\Translator|string|null $type_des
 * @method static Builder|WechatMenu newModelQuery()
 * @method static Builder|WechatMenu newQuery()
 * @method static Builder|WechatMenu query()
 * @method static Builder|WechatMenu whereAppid($value)
 * @method static Builder|WechatMenu whereDisplayorder($value)
 * @method static Builder|WechatMenu whereFid($value)
 * @method static Builder|WechatMenu whereId($value)
 * @method static Builder|WechatMenu whereKey($value)
 * @method static Builder|WechatMenu whereMediaId($value)
 * @method static Builder|WechatMenu whereName($value)
 * @method static Builder|WechatMenu wherePagepath($value)
 * @method static Builder|WechatMenu whereType($value)
 * @method static Builder|WechatMenu whereUrl($value)
 * @mixin \Eloquent
 */
class WechatMenu extends Model
{
    protected $table = 'wechat_menu';
    protected $primaryKey = 'id';
    protected $fillable = ['fid', 'name', 'type', 'key', 'media_id', 'url', 'appid', 'pagepath', 'displayorder'];
    protected $appends = ['type_des'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderBy('displayorder')->orderBy('id');
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany(WechatMenu::class, 'fid', 'id');
    }

    /**
     * @return array|\Illuminate\Contracts\Translation\Translator|string|null
     */
    public function getTypeDesAttribute()
    {
        return $this->type ? trans('wechat.menu_types.' . $this->type) : null;
    }
}
